artifact_uri: file:///d:/Proyectos/Portafolio/factored-datathon-2023-Big-Data-Joropo/notebook/mlruns/840637120476704508/3fb8bac74b3249b88ad720d6cddf920a/artifacts
end_time: 1690940086715
entry_point_name: ''
experiment_id: '840637120476704508'
lifecycle_stage: active
run_id: 3fb8bac74b3249b88ad720d6cddf920a
run_name: respected-snipe-14
run_uuid: 3fb8bac74b3249b88ad720d6cddf920a
source_name: ''
source_type: 4
source_version: ''
start_time: 1690940086657
status: 3
tags: []
user_id: laptop
