artifact_location: file:///d:/Proyectos/Portafolio/factored-datathon-2023-Big-Data-Joropo/notebook/mlruns/0
creation_time: 1690939872644
experiment_id: '0'
last_update_time: 1690939872644
lifecycle_stage: active
name: Default
