artifact_location: file:///d:/Proyectos/Portafolio/factored-datathon-2023-Big-Data-Joropo/notebook/mlruns/840637120476704508
creation_time: 1690939872682
experiment_id: '840637120476704508'
last_update_time: 1690939872682
lifecycle_stage: active
name: Joropo_Expreriment
